version: '3.7'

# starts 4 docker containers running minio server instances. Each
# minio server's web interface will be accessible on the host at port
# 9001 through 9004.
services:

  # whoami:
  #   image: nginxdemos/hello
  #   labels:
  #     - traefik.enable=true
  #     - traefik.docker.network=minio_minio-net
  #     - traefik.frontend.rule=PathPrefixStrip:/whoami
  #     - traefik.port=80

  traefik:
    image: traefik
    ports:
      - 8081:80
    command: traefik --docker --docker.endpoint=unix:///var/run/docker.sock --docker.watch --api
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==manager
    networks:
      - default
      - minio-net
    labels:
      - traefik.enable=true
      - traefik.docker.network=minio_minio-net
      - traefik.frontend.rule=PathPrefixStrip:/api
      - traefik.port=8080

  minio1:
    image: minio/minio:RELEASE.2019-08-29T00-25-01Z
    hostname: minio1
    volumes:
      - minio1-data:/export
    networks:
      - minio-net
    deploy:
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
    command: server /export
    secrets:
      - secret_key
      - access_key
    healthcheck:
      test: ["CMD", "curl", "-f", "http://minio1:9000/minio/health/live"]
      interval: 1m30s
      timeout: 20s
      retries: 3
      start_period: 3m
    labels:
      - traefik.enable=true
      - traefik.docker.network=minio_minio-net
      - traefik.frontend.rule=Host:devyn.cen.centeva.com
      - traefik.port=9000

  # minio2:
  #   image: minio/minio:RELEASE.2019-08-29T00-25-01Z
  #   hostname: minio2
  #   volumes:
  #     - minio2-data:/export
  #   networks:
  #     - minio-net
  #   deploy:
  #     restart_policy:
  #       delay: 10s
  #       max_attempts: 10
  #       window: 60s
  #   command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export
  #   secrets:
  #     - secret_key
  #     - access_key
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://minio2:9000/minio/health/live"]
  #     interval: 1m30s
  #     timeout: 20s
  #     retries: 3
  #     start_period: 3m
  #   labels:
  #     - traefik.enable=true
  #     - traefik.docker.network=minio_minio-net
  #     - traefik.frontend.rule=PathPrefixStrip:/minio2
  #     - traefik.port=9000

  # minio3:
  #   image: minio/minio:RELEASE.2019-08-29T00-25-01Z
  #   hostname: minio3
  #   volumes:
  #     - minio3-data:/export
  #   networks:
  #     - minio-net
  #   deploy:
  #     restart_policy:
  #       delay: 10s
  #       max_attempts: 10
  #       window: 60s
  #   command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export
  #   secrets:
  #     - secret_key
  #     - access_key
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://minio3:9000/minio/health/live"]
  #     interval: 1m30s
  #     timeout: 20s
  #     retries: 3
  #     start_period: 3m
  #   labels:
  #     - traefik.enable=true
  #     - traefik.docker.network=minio_minio-net
  #     - traefik.frontend.rule=PathPrefixStrip:/minio3
  #     - traefik.port=9000

  # minio4:
  #   image: minio/minio:RELEASE.2019-08-29T00-25-01Z
  #   hostname: minio4
  #   volumes:
  #     - minio4-data:/export
  #   networks:
  #     - minio-net
  #   deploy:
  #     restart_policy:
  #       delay: 10s
  #       max_attempts: 10
  #       window: 60s
  #   command: server http://minio1/export http://minio2/export http://minio3/export http://minio4/export
  #   secrets:
  #     - secret_key
  #     - access_key
  #   healthcheck:
  #     test: ["CMD", "curl", "-f", "http://minio4:9000/minio/health/live"]
  #     interval: 1m30s
  #     timeout: 20s
  #     retries: 3
  #     start_period: 3m
  #   labels:
  #     - traefik.enable=true
  #     - traefik.docker.network=minio_minio-net
  #     - traefik.frontend.rule=PathPrefixStrip:/minio4
  #     - traefik.port=9000

volumes:
  minio1-data:

  minio2-data:

  minio3-data:

  minio4-data:

networks:
  minio-net:
    driver: overlay

secrets:
  secret_key:
    external: true
  access_key:
    external: true